name: my-app
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: echo "installing.."
      - name: Lint
        run: echo "linting.."
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: echo "installing..""
      - name: test
        run: echo "testing..."
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: echo "installing.."
      - name: deploy
        run: echo "deploying.."