name: multi-job
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    types:
      - opened
      - closed
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: echo "installing.."
      - name: Lint
        run: echo "linting.."
  test: 
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: echo "installing.."
      - name: test
        run: echo "testing..."
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: echo "installing.."
      - name: deploy
        run: echo "deploying.."