name: my-app
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci 
      - name: Lint
        run: npm lint run 
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci 
      - name: Lint
        run: npm lint run
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci 
      - name: deploy
        run: echo "deploying.."